# Generated by Django 4.2.3 on 2023-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song", models.CharField(max_length=100)),
                ("previous_position", models.IntegerField(null=True)),
                ("current_position", models.IntegerField()),
            ],
        ),
    ]
