# Generated by Django 4.2.3 on 2023-07-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0002_rename_song_chart_title_chart_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="indicator",
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
