# Generated by Django 4.2.3 on 2023-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0003_chart_indicator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="indicator",
            field=models.IntegerField(),
        ),
    ]
