# Generated by Django 4.2.3 on 2023-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0005_alter_chart_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="competitor",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="chart",
            name="spot_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chart",
            name="spot_url",
            field=models.URLField(null=True),
        ),
    ]
