# Generated by Django 4.2.3 on 2023-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0006_chart_competitor_chart_spot_name_chart_spot_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chart",
            old_name="competitor",
            new_name="comp_url",
        ),
        migrations.AddField(
            model_name="chart",
            name="comp_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
