# Generated by Django 4.2.3 on 2023-07-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0007_rename_competitor_chart_comp_url_chart_comp_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="comp_artist",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chart",
            name="sound_likes",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="chart",
            name="sound_play",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="chart",
            name="sound_repost",
            field=models.IntegerField(null=True),
        ),
    ]
