# Generated by Django 4.2.3 on 2023-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0010_chart_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="tags",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
