# Generated by Django 4.2.3 on 2023-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0011_alter_chart_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="lastweek",
            field=models.IntegerField(null=True),
        ),
    ]
